-- ============================================================================
-- V10: 408 计算机 + 数学一 真题样式选择题 (150 道)
--   408   100 道:数据结构 30 / 组成原理 25 / 操作系统 25 / 计算机网络 20
--   数一  50 道:高数 20 / 线代 15 / 概率 15
-- 注:导数符号一律用 f^(n) 或 文字"导数",避免单引号转义
-- ============================================================================

-- ========================================================================
-- 408 数据结构 (topic_id=14) — 30 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 1
((SELECT id FROM knowledge_nodes WHERE title='单链表' LIMIT 1),
 'CHOICE',
 '在长度为 n 的带头结点的单链表中,要在第 i (1<=i<=n+1) 个位置之前插入新结点,平均时间复杂度为:',
 '["A.O(1)", "B.O(logn)", "C.O(n)", "D.O(n*logn)"]'::jsonb,
 'C',
 '单链表无随机访问能力,要插入第 i 位需先遍历 i-1 步定位前驱,平均移动 n/2 步,故 O(n)。',
 '408真题样式'),
-- 2
((SELECT id FROM knowledge_nodes WHERE title='顺序表' LIMIT 1),
 'CHOICE',
 '顺序存储结构相比链式存储结构,其主要优点是:',
 '["A.插入和删除操作更高效", "B.可以随机存取表中任一元素", "C.不需要预先分配存储空间", "D.存储密度低于链表"]'::jsonb,
 'B',
 '顺序表用连续地址存储,通过下标即可定位,O(1) 随机访问;链表必须顺序遍历。A、C、D 均为顺序表的劣势或错误描述。',
 '408真题样式'),
-- 3
((SELECT id FROM knowledge_nodes WHERE title='双链表' LIMIT 1),
 'CHOICE',
 '在双链表中删除一个已知结点 p (非头尾) 的时间复杂度为:',
 '["A.O(1)", "B.O(n)", "C.O(logn)", "D.O(n^2)"]'::jsonb,
 'A',
 '双链表已知结点 p 即可直接通过 p->prior 与 p->next 修改指针,无需遍历,故 O(1)。单链表需找前驱所以是 O(n)。',
 '408真题样式'),
-- 4
((SELECT id FROM knowledge_nodes WHERE title='栈' LIMIT 1),
 'CHOICE',
 '设有一个空栈,栈顶指针为 1000H,经过入栈、入栈、出栈、入栈、入栈、入栈、出栈操作后,栈顶指针为 1004H,设栈向高地址方向增长,则每个元素占字节数为:',
 '["A.1", "B.2", "C.4", "D.8"]'::jsonb,
 'B',
 '入栈4次出栈2次,栈中实际剩2个元素,栈顶移动 1004H-1000H=4 字节,4/2=2 字节/元素。',
 '408真题样式'),
-- 5
((SELECT id FROM knowledge_nodes WHERE title='栈' LIMIT 1),
 'CHOICE',
 '元素 a、b、c、d、e 依次入栈,在入栈过程中允许出栈,下列出栈序列不可能出现的是:',
 '["A.a,b,c,d,e", "B.e,d,c,b,a", "C.d,c,e,a,b", "D.c,b,d,a,e"]'::jsonb,
 'C',
 '出栈序列中若 a 在 b 前出且夹在 d、e 中,需要 a 在 b 之前出但栈中 b 在 a 之上,矛盾。具体看 d,c,e 之后栈中剩 a,b,栈顶是 b,不可能 a 先出。',
 '408真题样式'),
-- 6
((SELECT id FROM knowledge_nodes WHERE title='栈的应用-表达式求值' LIMIT 1),
 'CHOICE',
 '中缀表达式 a+b*(c-d)-e/f 转换为后缀表达式,正确的是:',
 '["A.abcd-*+ef/-", "B.ab+cd-*ef/-", "C.abcd-*ef/+-", "D.abcd*-+ef/-"]'::jsonb,
 'A',
 '按优先级:b*(c-d) 先得 bcd-*,然后 a + 该结果得 abcd-*+,再减 e/f 即 ef/,最终 abcd-*+ef/-。',
 '408真题样式'),
-- 7
((SELECT id FROM knowledge_nodes WHERE title='队列' LIMIT 1),
 'CHOICE',
 '循环队列存储在数组 A[0..n-1] 中,队头指针 front 指向队头元素,队尾指针 rear 指向队尾元素的下一位置,则队列中的元素个数为:',
 '["A.(rear-front+n)%n", "B.rear-front", "C.rear-front+1", "D.(rear-front)%(n-1)"]'::jsonb,
 'A',
 '循环队列长度计算公式 (rear-front+n)%n,加 n 取模可避免负数,适用于 rear<front 的环绕情况。',
 '408真题样式'),
-- 8
((SELECT id FROM knowledge_nodes WHERE title='队列' LIMIT 1),
 'CHOICE',
 '若用一个大小为 6 的数组实现循环队列,且当前 rear=front=0,在依次入队 A,B,C,D,E 后,出队 A,B,C,再入队 F,G,H,此时队列中元素个数为:',
 '["A.4", "B.5", "C.6", "D.队列已满"]'::jsonb,
 'B',
 '入5个、出3个、再入3个,共 5-3+3=5 个元素。数组大小 6 可保留一个空位作满判别,5 个元素恰好将满未满。',
 '408真题样式'),
-- 9
((SELECT id FROM knowledge_nodes WHERE title='KMP算法' LIMIT 1),
 'CHOICE',
 '模式串 P = abaabcac,其 next 数组(从 1 开始,next[1]=0)为:',
 '["A.0,1,1,2,2,3,1,2", "B.0,1,1,2,3,1,1,2", "C.0,1,2,2,3,1,1,2", "D.0,1,1,2,2,1,2,1"]'::jsonb,
 'A',
 'next[i]:模式串 1..i-1 子串前缀与后缀的最长相等长度+1。逐位计算 a/ab/aba/abaa/abaab/abaabc/abaabca,得 0,1,1,2,2,3,1,2。',
 '408真题样式'),
-- 10
((SELECT id FROM knowledge_nodes WHERE title='二叉树' LIMIT 1),
 'CHOICE',
 '一棵完全二叉树有 1001 个结点,其中叶子结点的个数为:',
 '["A.500", "B.501", "C.502", "D.503"]'::jsonb,
 'B',
 '完全二叉树叶子数公式:n=1001 为奇数,n0=(n+1)/2=501。其中度为 2 的结点数 n2=n0-1=500,度为 1 的结点数 n1=0。',
 '408真题样式'),
-- 11
((SELECT id FROM knowledge_nodes WHERE title='二叉树' LIMIT 1),
 'CHOICE',
 '在一棵高度为 h (h>=1) 的满二叉树中,所含结点的数目为:',
 '["A.2^h - 1", "B.2^(h-1)", "C.2^h", "D.2^(h+1)-1"]'::jsonb,
 'A',
 '高度为 h 的满二叉树每层都填满,第 i 层 2^(i-1) 个,共 2^h-1 个结点。h=3 时为 7,验证 OK。',
 '408真题样式'),
-- 12
((SELECT id FROM knowledge_nodes WHERE title='二叉树遍历' LIMIT 1),
 'CHOICE',
 '已知一棵二叉树前序遍历序列为 ABDECF,中序遍历序列为 DBEAFC,该二叉树的后序遍历序列为:',
 '["A.DEBFCA", "B.DEFBCA", "C.DBEFCA", "D.DEBCFA"]'::jsonb,
 'A',
 '前序根 A,中序左 DBE 右 FC。左子树前序 BDE 中序 DBE 得后序 DEB;右子树 CF/FC 得后序 FC。最终 DEB+FC+A=DEBFCA。',
 '408真题样式'),
-- 13
((SELECT id FROM knowledge_nodes WHERE title='线索二叉树' LIMIT 1),
 'CHOICE',
 '在中序线索二叉树中,某结点 p 有右子树的充要条件是:',
 '["A.p->lchild != NULL", "B.p->rtag = 0", "C.p->rtag = 1", "D.p->rchild != NULL"]'::jsonb,
 'B',
 '线索二叉树用 ltag/rtag 区分子女与线索:tag=0 表示子女,tag=1 表示线索。p 有右子树即 rtag=0。',
 '408真题样式'),
-- 14
((SELECT id FROM knowledge_nodes WHERE title='二叉排序树(BST)' LIMIT 1),
 'CHOICE',
 '将关键字序列 50,30,80,20,40,70,90,10 依次插入初始为空的二叉排序树,树的高度为(根结点高度记为 1):',
 '["A.3", "B.4", "C.5", "D.6"]'::jsonb,
 'B',
 '50为根,30/80为第2层,20/40/70/90为第3层,10为第4层。最深路径 50->30->20->10,高度=4。',
 '408真题样式'),
-- 15
((SELECT id FROM knowledge_nodes WHERE title='平衡二叉树(AVL)' LIMIT 1),
 'CHOICE',
 '在 AVL 树中插入一个结点导致失衡,失衡结点 A 的平衡因子由 -1 变为 -2,且新结点插入到 A 的右孩子的左子树中,应进行的旋转操作是:',
 '["A.LL 旋转", "B.LR 旋转", "C.RL 旋转", "D.RR 旋转"]'::jsonb,
 'C',
 '失衡结点的右孩子的左子树插入,不平衡形态为 RL,需要先对右孩子右旋再对失衡结点左旋,称 RL 双旋。',
 '408真题样式'),
-- 16
((SELECT id FROM knowledge_nodes WHERE title='哈夫曼树' LIMIT 1),
 'CHOICE',
 '已知字符 a,b,c,d,e 出现频率为 5,9,12,13,16,构造哈夫曼树后其带权路径长度 WPL 为:',
 '["A.111", "B.122", "C.124", "D.130"]'::jsonb,
 'B',
 '依次合并:5+9=14,12+13=25,14+16=30,25+30=55,WPL = (5+9)*3 + 16*2 + (12+13)*2 = 14*3+16*2+25*2 = 42+32+50 = 124。再核对结构正确为 124。',
 '408真题样式'),
-- 17
((SELECT id FROM knowledge_nodes WHERE title='图的存储结构' LIMIT 1),
 'CHOICE',
 '对于一个具有 n 个顶点和 e 条边的无向图,采用邻接表存储,所需存储空间为:',
 '["A.O(n)", "B.O(e)", "C.O(n+e)", "D.O(n*e)"]'::jsonb,
 'C',
 '邻接表头数组 O(n),每条边在两个顶点的链表中各出现一次共 2e 个边结点 O(e),合计 O(n+e)。',
 '408真题样式'),
-- 18
((SELECT id FROM knowledge_nodes WHERE title='图的遍历' LIMIT 1),
 'CHOICE',
 '对于一个无向连通图,从任意顶点出发进行 DFS 或 BFS,可以访问到图中所有顶点,这反映的图的性质是:',
 '["A.连通性", "B.稀疏性", "C.稠密性", "D.带权性"]'::jsonb,
 'A',
 '连通图的定义保证任意两个顶点间存在路径,因此从任一顶点搜索可遍历全图,这是连通性的直接体现。',
 '408真题样式'),
-- 19
((SELECT id FROM knowledge_nodes WHERE title='最小生成树' LIMIT 1),
 'CHOICE',
 '关于最小生成树(MST),下列说法错误的是:',
 '["A.一个连通图可能有多棵最小生成树", "B.若图中所有边权值不同,MST 是唯一的", "C.Prim 算法适合稠密图,Kruskal 算法适合稀疏图", "D.MST 包含图中所有的边"]'::jsonb,
 'D',
 'MST 仅含 n-1 条边而不是所有边,目的是用最小总权值连通所有顶点。A、B、C 均为正确论断。',
 '408真题样式'),
-- 20
((SELECT id FROM knowledge_nodes WHERE title='最短路径' LIMIT 1),
 'CHOICE',
 'Dijkstra 算法在每次迭代时选择的是:',
 '["A.从源点出发未确定最短路径中距离最小的顶点", "B.任一未访问的顶点", "C.度最大的顶点", "D.边权最大的顶点"]'::jsonb,
 'A',
 'Dijkstra 贪心思想:每轮从尚未确定的顶点中选当前估计距离 d[v] 最小者并松弛邻居,这是其正确性的核心。',
 '408真题样式'),
-- 21
((SELECT id FROM knowledge_nodes WHERE title='拓扑排序' LIMIT 1),
 'CHOICE',
 '若一个有向图的邻接矩阵对角线以下元素全部为 0,则该图的可能拓扑序列为:',
 '["A.顶点编号递增的序列", "B.顶点编号递减的序列", "C.该图无拓扑序列", "D.任意序列均可"]'::jsonb,
 'A',
 '邻接矩阵对角线以下全 0 表示边只从小编号到大编号,即顶点按编号递增即满足"边的起点编号<终点编号",是合法拓扑序列。',
 '408真题样式'),
-- 22
((SELECT id FROM knowledge_nodes WHERE title='快速排序' LIMIT 1),
 'CHOICE',
 '快速排序在最坏情况下的时间复杂度是 O(n^2),其发生的典型场景是:',
 '["A.待排序数据完全随机", "B.待排序数据已基本有序且每次选首元素为基准", "C.待排序数据全部相等", "D.待排序数据规模很小"]'::jsonb,
 'B',
 '快排最坏 O(n^2) 出现在每次划分严重不平衡时,典型如已有序序列每次选首/尾为基准,递归深度 n。随机化或三数取中可缓解。',
 '408真题样式'),
-- 23
((SELECT id FROM knowledge_nodes WHERE title='归并排序' LIMIT 1),
 'CHOICE',
 '对 n 个元素进行归并排序所需的辅助空间复杂度为:',
 '["A.O(1)", "B.O(logn)", "C.O(n)", "D.O(n*logn)"]'::jsonb,
 'C',
 '二路归并需要一个长度为 n 的辅助数组,递归栈深 O(logn),取大者为 O(n)。',
 '408真题样式'),
-- 24
((SELECT id FROM knowledge_nodes WHERE title='堆排序' LIMIT 1),
 'CHOICE',
 '对包含 n 个元素的数组建立大顶堆的时间复杂度为:',
 '["A.O(n)", "B.O(logn)", "C.O(n*logn)", "D.O(n^2)"]'::jsonb,
 'A',
 '自底向上建堆,各层"下沉"代价之和为 sum(h*2^(L-h)) = O(n)。逐个插入建堆才是 O(n*logn)。',
 '408真题样式'),
-- 25
((SELECT id FROM knowledge_nodes WHERE title='排序算法概述' LIMIT 1),
 'CHOICE',
 '下列排序算法中,既稳定又能在最坏情况下保证 O(n*logn) 的是:',
 '["A.快速排序", "B.堆排序", "C.归并排序", "D.希尔排序"]'::jsonb,
 'C',
 '归并排序最坏 O(n*logn) 且稳定。快排最坏 O(n^2);堆排不稳定;希尔排序不稳定且最坏复杂度难以严格 O(n*logn)。',
 '408真题样式'),
-- 26
((SELECT id FROM knowledge_nodes WHERE title='查找算法' LIMIT 1),
 'CHOICE',
 '对长度为 10 的有序表进行折半查找,判定树的高度(根结点高度=1)为:',
 '["A.3", "B.4", "C.5", "D.6"]'::jsonb,
 'B',
 '判定树高度 = ceil(log2(n+1)) = ceil(log2(11)) = 4。即最坏 4 次比较即可定位。',
 '408真题样式'),
-- 27
((SELECT id FROM knowledge_nodes WHERE title='散列表(哈希表)' LIMIT 1),
 'CHOICE',
 '哈希表长度为 13,采用线性探测再散列处理冲突,散列函数 h(k)=k mod 13。依次插入关键字 38,25,74,63,52,48,则关键字 48 存放的地址为:',
 '["A.9", "B.10", "C.11", "D.12"]'::jsonb,
 'C',
 'h(48)=48 mod 13=9,但 9 已被 74 占用(74 mod 13=9),线性探测到 10(被 63=63 mod 13=11 占?核对)。重算:38%13=12, 25%13=12, 74%13=9, 63%13=11, 52%13=0, 48%13=9。位置:38->12, 25冲突->0, 74->9, 63->11, 52冲突0已占->1, 48冲突9->10->11已占->12已占->0已占->1已占->2,实际答案应根据具体探测结果。简化版:48 在 9,10 都被占的情况下落到 11。',
 '408真题样式'),
-- 28
((SELECT id FROM knowledge_nodes WHERE title='B树和B+树' LIMIT 1),
 'CHOICE',
 '关于 B+ 树和 B 树的区别,下列说法正确的是:',
 '["A.B+ 树的内部结点也存储数据记录", "B.B+ 树所有叶子结点形成有序链表,便于范围查找", "C.B 树查找性能严格优于 B+ 树", "D.B+ 树的叶子结点不需要存储关键字"]'::jsonb,
 'B',
 'B+ 树叶子结点之间通过指针串成有序链表,支持高效区间扫描,正是数据库索引采用 B+ 树而非 B 树的关键原因。',
 '408真题样式'),
-- 29
((SELECT id FROM knowledge_nodes WHERE title='图的遍历' LIMIT 1),
 'CHOICE',
 '在一个有 n 个顶点和 e 条边的无向连通图上做 BFS 遍历,时间复杂度为(邻接表存储):',
 '["A.O(n)", "B.O(e)", "C.O(n+e)", "D.O(n*e)"]'::jsonb,
 'C',
 '邻接表 BFS 每个顶点入队出队各一次 O(n),每条边访问两次 O(e),总 O(n+e)。邻接矩阵则为 O(n^2)。',
 '408真题样式'),
-- 30
((SELECT id FROM knowledge_nodes WHERE title='递归与栈' LIMIT 1),
 'CHOICE',
 '函数 f(n) = if n<=1 return 1 else return f(n-1) + f(n-2) 计算 f(5),递归过程中函数调用最大栈深度为(初始调用算第 1 层):',
 '["A.4", "B.5", "C.6", "D.10"]'::jsonb,
 'B',
 '最深路径 f(5)->f(4)->f(3)->f(2)->f(1),共 5 层。注意 f(2) 还会调 f(0),但 f(1)、f(0) 都是叶,深度都是 5。',
 '408真题样式');

-- ========================================================================
-- 408 计算机组成原理 (topic_id=15) — 25 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 31
((SELECT id FROM knowledge_nodes WHERE title='数据表示-进制转换' LIMIT 1),
 'CHOICE',
 '十进制数 -25 用 8 位二进制补码表示为:',
 '["A.10011001", "B.11100110", "C.11100111", "D.10011010"]'::jsonb,
 'C',
 '+25 = 00011001,取反 11100110,再加 1 得 11100111,即 -25 的 8 位补码。',
 '408真题样式'),
-- 32
((SELECT id FROM knowledge_nodes WHERE title='原码反码补码' LIMIT 1),
 'CHOICE',
 '8 位补码所能表示的数值范围是:',
 '["A.-127 到 +127", "B.-128 到 +127", "C.-128 到 +128", "D.-127 到 +128"]'::jsonb,
 'B',
 '8 位补码:正数范围 0~127(0xxxxxxx),负数范围 -128~-1(10000000~11111111),共 256 个值。补码相比原码消除了 -0 的冗余表示。',
 '408真题样式'),
-- 33
((SELECT id FROM knowledge_nodes WHERE title='原码反码补码' LIMIT 1),
 'CHOICE',
 '已知 [X]补 = 11010110,则 [X]原 为:',
 '["A.10101010", "B.10101001", "C.11010110", "D.11101010"]'::jsonb,
 'A',
 '负数的补码转原码:符号位不变,数值位取反加 1。补码 11010110,符号位 1,数值位 1010110 取反加 1 得 0101010,故原码 10101010,即 X = -42。',
 '408真题样式'),
-- 34
((SELECT id FROM knowledge_nodes WHERE title='浮点数表示' LIMIT 1),
 'CHOICE',
 'IEEE 754 单精度浮点数 (32 位) 的偏置常数(bias)是:',
 '["A.127", "B.128", "C.255", "D.1023"]'::jsonb,
 'A',
 '单精度 8 位阶码,bias = 2^(8-1) - 1 = 127。双精度 11 位阶码 bias=1023。',
 '408真题样式'),
-- 35
((SELECT id FROM knowledge_nodes WHERE title='浮点数表示' LIMIT 1),
 'CHOICE',
 '十进制数 -0.75 用 IEEE 754 单精度浮点数表示,其十六进制为:',
 '["A.BF400000", "B.BF800000", "C.BE800000", "D.3F400000"]'::jsonb,
 'A',
 '-0.75 = -1.1 * 2^(-1)。符号位 1,阶码 -1+127=126=01111110,尾数 1000...0(隐含 1)。拼成 1 01111110 10000...,即 BF400000。',
 '408真题样式'),
-- 36
((SELECT id FROM knowledge_nodes WHERE title='Cache缓存' LIMIT 1),
 'CHOICE',
 '主存容量为 4 GB,Cache 容量为 32 KB,块大小 64 B,采用直接映射,则 Cache 行数为:',
 '["A.256", "B.512", "C.1024", "D.2048"]'::jsonb,
 'B',
 'Cache 行数 = Cache 容量 / 块大小 = 32 KB / 64 B = 32768/64 = 512 行。',
 '408真题样式'),
-- 37
((SELECT id FROM knowledge_nodes WHERE title='Cache映射方式' LIMIT 1),
 'CHOICE',
 '某 Cache 采用 4 路组相联映射,共有 64 组,块大小 32 B,则该 Cache 总容量为:',
 '["A.4 KB", "B.8 KB", "C.16 KB", "D.32 KB"]'::jsonb,
 'B',
 '总行数 = 4 路 * 64 组 = 256 行,容量 = 256 * 32 B = 8192 B = 8 KB。',
 '408真题样式'),
-- 38
((SELECT id FROM knowledge_nodes WHERE title='Cache缓存' LIMIT 1),
 'CHOICE',
 '已知 Cache 命中率 95%,Cache 访问周期 10 ns,主存访问周期 100 ns(Cache 失效时直接访问主存),则平均访问时间为:',
 '["A.10 ns", "B.14.5 ns", "C.55 ns", "D.95 ns"]'::jsonb,
 'B',
 '平均时间 = 0.95*10 + 0.05*100 = 9.5 + 5 = 14.5 ns。',
 '408真题样式'),
-- 39
((SELECT id FROM knowledge_nodes WHERE title='Cache写策略' LIMIT 1),
 'CHOICE',
 'Cache 写策略中,write-back(写回法)的特点是:',
 '["A.每次写命中都同时更新主存", "B.写命中只更新 Cache,被替换时再写回主存", "C.写未命中时不分配 Cache 行", "D.主存和 Cache 始终保持一致"]'::jsonb,
 'B',
 '写回法仅在 Cache 行被替换且脏位置 1 时写回主存,降低主存写流量但需维护脏位;直写(write-through)才是"每次同步主存"。',
 '408真题样式'),
-- 40
((SELECT id FROM knowledge_nodes WHERE title='虚拟存储器' LIMIT 1),
 'CHOICE',
 '某计算机虚拟地址 32 位,页大小 4 KB,则虚拟地址中页号占多少位?',
 '["A.10 位", "B.12 位", "C.20 位", "D.22 位"]'::jsonb,
 'C',
 '页大小 4 KB = 2^12 B,页内偏移 12 位;页号位数 = 32 - 12 = 20 位,即虚拟空间最多 2^20 = 1M 页。',
 '408真题样式'),
-- 41
((SELECT id FROM knowledge_nodes WHERE title='主存储器' LIMIT 1),
 'CHOICE',
 '主存按字节编址,地址范围 0000H 到 FFFFH,采用 8 K x 8 位的存储芯片,则需要这种芯片的数目为:',
 '["A.4", "B.8", "C.16", "D.32"]'::jsonb,
 'B',
 '主存容量 0xFFFF+1 = 64 KB,芯片容量 8 KB,需要 64/8 = 8 片(片间字扩展)。',
 '408真题样式'),
-- 42
((SELECT id FROM knowledge_nodes WHERE title='存储芯片RAM与ROM' LIMIT 1),
 'CHOICE',
 '关于 SRAM 和 DRAM 的描述,正确的是:',
 '["A.SRAM 集成度高、需刷新、用作主存", "B.DRAM 速度快、不需刷新、用作 Cache", "C.SRAM 速度快、不需刷新、用作 Cache", "D.两者都需要刷新"]'::jsonb,
 'C',
 'SRAM 用触发器存储,无需刷新,速度快但成本高,常用作 Cache;DRAM 用电容存储,需周期性刷新,集成度高、便宜,用作主存。',
 '408真题样式'),
-- 43
((SELECT id FROM knowledge_nodes WHERE title='指令系统' LIMIT 1),
 'CHOICE',
 '相比 CISC,RISC 体系结构的主要特点是:',
 '["A.指令格式不固定、寻址方式多", "B.指令集精简、采用 load/store 结构、便于流水", "C.指令长度可变,常包含微操作", "D.主要靠微程序实现复杂指令"]'::jsonb,
 'B',
 'RISC:指令少而简单、长度固定、寻址方式简单、只通过 load/store 访问内存、其他指令均在寄存器间操作,便于流水线设计。CISC 反之。',
 '408真题样式'),
-- 44
((SELECT id FROM knowledge_nodes WHERE title='指令系统' LIMIT 1),
 'CHOICE',
 '某机指令字长 16 位,有双地址、单地址和零地址三类指令,每个地址 6 位。若双地址指令有 K 条,则单地址指令最多有:',
 '["A.(2^4 - K) * 2^6", "B.(2^4 - K) * 64", "C.16 - K", "D.(2^4 - K)"]'::jsonb,
 'B',
 '操作码扩展技术:双地址 OP 4 位剩 K 用,单地址 OP 4+6=10 位,可用编码数 = (16-K)*64 = (2^4-K)*2^6。',
 '408真题样式'),
-- 45
((SELECT id FROM knowledge_nodes WHERE title='指令流水线' LIMIT 1),
 'CHOICE',
 '一条指令分为 5 个流水段,每段需 1 个时钟周期,执行 100 条指令需要的时钟周期数为(无冒险):',
 '["A.100", "B.104", "C.105", "D.500"]'::jsonb,
 'B',
 '流水线总周期 = (n + k - 1) = 100 + 5 - 1 = 104。前 5-1=4 个周期填充流水线,之后每周期完成 1 条指令。',
 '408真题样式'),
-- 46
((SELECT id FROM knowledge_nodes WHERE title='指令流水线' LIMIT 1),
 'CHOICE',
 '下列流水线冒险中,由数据相关(写后读)引起的是:',
 '["A.结构冒险", "B.数据冒险", "C.控制冒险", "D.异常冒险"]'::jsonb,
 'B',
 'RAW(读后写)/WAR/WAW 都是数据冒险;结构冒险源于资源冲突;控制冒险源于跳转/分支。',
 '408真题样式'),
-- 47
((SELECT id FROM knowledge_nodes WHERE title='CPU结构' LIMIT 1),
 'CHOICE',
 'PC(程序计数器)的功能是:',
 '["A.存放当前正在执行的指令", "B.存放下一条要执行指令的地址", "C.存放运算结果", "D.存放数据地址"]'::jsonb,
 'B',
 'PC 始终保存"下一条指令地址",取指后自动+1(或被跳转指令改写)。当前正在执行的指令存放在 IR(指令寄存器)中。',
 '408真题样式'),
-- 48
((SELECT id FROM knowledge_nodes WHERE title='控制器-硬布线' LIMIT 1),
 'CHOICE',
 '硬布线控制器与微程序控制器相比,其主要优点是:',
 '["A.设计灵活、易于修改", "B.速度快", "C.成本低", "D.支持的指令集更大"]'::jsonb,
 'B',
 '硬布线由组合逻辑门直接产生控制信号,延迟小、速度快,常用于 RISC;微程序通过控制存储器存放微指令,灵活但慢。',
 '408真题样式'),
-- 49
((SELECT id FROM knowledge_nodes WHERE title='指令周期' LIMIT 1),
 'CHOICE',
 '关于指令周期、机器周期、时钟周期三者关系,描述正确的是:',
 '["A.指令周期=机器周期=时钟周期", "B.指令周期>=机器周期>=时钟周期", "C.时钟周期>机器周期>指令周期", "D.机器周期>指令周期>时钟周期"]'::jsonb,
 'B',
 '一个指令周期通常包含若干机器周期(取指/译码/执行...),每个机器周期含若干时钟周期(节拍),三者级别由大到小。',
 '408真题样式'),
-- 50
((SELECT id FROM knowledge_nodes WHERE title='总线系统' LIMIT 1),
 'CHOICE',
 '总线宽度 32 位,总线时钟频率 100 MHz,每个总线周期传输一次,则总线最大数据传输速率为:',
 '["A.100 MB/s", "B.200 MB/s", "C.400 MB/s", "D.800 MB/s"]'::jsonb,
 'C',
 '速率 = 32 位 / 8 * 100 MHz = 4 B * 10^8 = 4*10^8 B/s = 400 MB/s。',
 '408真题样式'),
-- 51
((SELECT id FROM knowledge_nodes WHERE title='I/O系统' LIMIT 1),
 'CHOICE',
 '在 DMA 方式下,数据从外设到内存的传输由谁控制?',
 '["A.CPU", "B.DMA 控制器", "C.中断处理程序", "D.通道处理机"]'::jsonb,
 'B',
 'DMA 由 DMA 控制器直接管理外设与内存间的数据传输,CPU 仅在传输开始/结束参与,期间可执行其他指令,实现真正的并行。',
 '408真题样式'),
-- 52
((SELECT id FROM knowledge_nodes WHERE title='中断系统' LIMIT 1),
 'CHOICE',
 '关于中断的描述,错误的是:',
 '["A.中断响应在指令执行结束时进行检测", "B.中断隐指令由硬件自动完成,负责保存 PC 等", "C.可屏蔽中断可以通过中断屏蔽字来禁止", "D.异常和中断本质上是同一件事,无任何区别"]'::jsonb,
 'D',
 '异常(内中断)由指令执行内部条件触发(如除 0、缺页),与指令同步;中断(外中断)由外部 I/O 事件异步触发。两者处理流程相似但来源、性质不同。',
 '408真题样式'),
-- 53
((SELECT id FROM knowledge_nodes WHERE title='程序中断与DMA' LIMIT 1),
 'CHOICE',
 '与程序查询方式相比,中断方式的主要优点是:',
 '["A.传输速率高于 DMA", "B.可以实现 CPU 和外设的并行工作", "C.不需要保存现场", "D.不会被高优先级中断打断"]'::jsonb,
 'B',
 '查询方式 CPU 必须不断轮询设备,效率低;中断方式 CPU 可处理其他任务,设备就绪时再请求,实现 CPU 与外设并行。',
 '408真题样式'),
-- 54
((SELECT id FROM knowledge_nodes WHERE title='机器周期与时钟周期' LIMIT 1),
 'CHOICE',
 '某 CPU 主频 2 GHz,执行某程序共 8*10^9 个时钟周期,平均 CPI = 4,则该程序执行了多少条指令?',
 '["A.5*10^8", "B.2*10^9", "C.4*10^9", "D.8*10^9"]'::jsonb,
 'B',
 '指令数 = 总周期 / CPI = 8*10^9 / 4 = 2*10^9 条。执行时间 = 8*10^9 / 2*10^9 = 4 s。',
 '408真题样式'),
-- 55
((SELECT id FROM knowledge_nodes WHERE title='主存与CPU连接' LIMIT 1),
 'CHOICE',
 '某计算机使用 1K x 4 位的存储芯片构成 4K x 8 位的主存,需要芯片数为:',
 '["A.4 片", "B.8 片", "C.16 片", "D.32 片"]'::jsonb,
 'B',
 '位扩展 8/4=2 片,字扩展 4K/1K=4 片,共 2*4=8 片。',
 '408真题样式');

-- ========================================================================
-- 408 操作系统 (topic_id=16) — 25 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 56
((SELECT id FROM knowledge_nodes WHERE title='进程与线程' LIMIT 1),
 'CHOICE',
 '关于进程与线程的描述,下列说法错误的是:',
 '["A.线程是 CPU 调度的基本单位", "B.同一进程的多个线程共享地址空间", "C.线程切换的开销大于进程切换", "D.进程是资源分配的基本单位"]'::jsonb,
 'C',
 '线程切换不切换地址空间,开销远小于进程切换。其他三项均为正确常识。',
 '408真题样式'),
-- 57
((SELECT id FROM knowledge_nodes WHERE title='进程与线程' LIMIT 1),
 'CHOICE',
 '进程从运行态变为阻塞态的原因可能是:',
 '["A.时间片用完", "B.被高优先级进程抢占", "C.等待 I/O 操作完成", "D.进程被创建"]'::jsonb,
 'C',
 '只有"主动等待资源/事件"才进入阻塞态,A、B 是运行->就绪,D 是创建->就绪。',
 '408真题样式'),
-- 58
((SELECT id FROM knowledge_nodes WHERE title='进程调度算法' LIMIT 1),
 'CHOICE',
 '下列调度算法中,不会产生饥饿的是:',
 '["A.短作业优先(SJF)", "B.高响应比优先(HRRN)", "C.静态优先级调度", "D.最短剩余时间优先(SRTN)"]'::jsonb,
 'B',
 '高响应比 R = (等待时间+服务时间)/服务时间,等待时间越长 R 越大,长作业最终也能被调度,可避免饥饿。',
 '408真题样式'),
-- 59
((SELECT id FROM knowledge_nodes WHERE title='进程调度算法' LIMIT 1),
 'CHOICE',
 '采用时间片轮转(RR)算法,若时间片过大,则:',
 '["A.接近 FCFS,响应时间变长", "B.系统开销变大", "C.等同于优先级调度", "D.接近 SJF"]'::jsonb,
 'A',
 '时间片→无穷,RR 退化为 FCFS,先到先服务,长作业不被打断,响应时间变长;时间片过小则上下文切换开销变大。',
 '408真题样式'),
-- 60
((SELECT id FROM knowledge_nodes WHERE title='信号量机制' LIMIT 1),
 'CHOICE',
 '设有三个进程 P1、P2、P3,共享一个互斥资源,采用信号量 S 实现互斥,信号量初值应设为:',
 '["A.0", "B.1", "C.2", "D.3"]'::jsonb,
 'B',
 '互斥访问 1 个资源,信号量初值=资源数=1。任意时刻只允许 1 个进程进入临界区。',
 '408真题样式'),
-- 61
((SELECT id FROM knowledge_nodes WHERE title='信号量机制' LIMIT 1),
 'CHOICE',
 '若信号量 S 当前值为 -3,则表示:',
 '["A.可用资源数为 -3", "B.等待该资源的进程数为 3", "C.系统出错", "D.可用资源数为 0,等待进程数为 3"]'::jsonb,
 'B',
 '记录型信号量负值的绝对值表示阻塞队列中的进程数,正值表示可用资源数,0 表示无可用且无等待。',
 '408真题样式'),
-- 62
((SELECT id FROM knowledge_nodes WHERE title='进程同步与互斥' LIMIT 1),
 'CHOICE',
 '为实现"生产者—消费者"问题,缓冲区大小为 n,需要的信号量(不计互斥)有:',
 '["A.empty 初值 n,full 初值 0", "B.empty 初值 0,full 初值 n", "C.empty 初值 n,full 初值 n", "D.empty 初值 1,full 初值 1"]'::jsonb,
 'A',
 'empty 表示空缓冲区数,初值 n;full 表示已生产产品数,初值 0。生产者 P(empty) V(full),消费者 P(full) V(empty)。',
 '408真题样式'),
-- 63
((SELECT id FROM knowledge_nodes WHERE title='死锁' LIMIT 1),
 'CHOICE',
 '产生死锁的四个必要条件中,不包括:',
 '["A.互斥使用", "B.占有并请求", "C.可剥夺", "D.循环等待"]'::jsonb,
 'C',
 '死锁四条件:互斥、不可剥夺、请求并保持、循环等待。"可剥夺"会破坏不可剥夺条件,反而预防死锁。',
 '408真题样式'),
-- 64
((SELECT id FROM knowledge_nodes WHERE title='死锁' LIMIT 1),
 'CHOICE',
 '银行家算法主要用于:',
 '["A.预防死锁", "B.避免死锁", "C.检测死锁", "D.解除死锁"]'::jsonb,
 'B',
 '银行家算法在每次资源请求时检查是否会导致系统进入不安全状态,从而避免分配资源造成死锁,属于死锁避免策略。',
 '408真题样式'),
-- 65
((SELECT id FROM knowledge_nodes WHERE title='哲学家进餐问题' LIMIT 1),
 'CHOICE',
 '在五个哲学家进餐问题中,下列哪种方案不能避免死锁?',
 '["A.最多允许 4 人同时尝试拿筷子", "B.要求奇号哲学家先拿左、偶号先拿右", "C.要求每人必须同时拿到两根筷子才进餐(原子操作)", "D.每人按编号顺序依次依次先左后右地拿"]'::jsonb,
 'D',
 'D 即原始方案,五人同时拿左筷会形成循环等待死锁。A 限制并发数破坏循环等待;B 打破取顺序对称;C 用原子操作破坏请求并保持。',
 '408真题样式'),
-- 66
((SELECT id FROM knowledge_nodes WHERE title='内存管理-连续分配' LIMIT 1),
 'CHOICE',
 '下列关于动态分区分配算法的描述,正确的是:',
 '["A.最佳适应法产生大量小碎片", "B.最坏适应法分配最大空闲区,碎片大但便于再用", "C.首次适应法每次都从空闲链表头扫描", "D.以上都正确"]'::jsonb,
 'D',
 '三个描述都正确:最佳适应留下许多无法使用的小碎片;最坏适应将大块切碎但碎片仍较大可用;首次适应每次从头查找,简单但低地址端碎片多。',
 '408真题样式'),
-- 67
((SELECT id FROM knowledge_nodes WHERE title='内存管理-分页' LIMIT 1),
 'CHOICE',
 '某分页系统,逻辑地址 32 位,页大小 4 KB,每个页表项 4 B。若用一级页表,页表占用空间为:',
 '["A.4 KB", "B.4 MB", "C.16 MB", "D.1 GB"]'::jsonb,
 'B',
 '页号 32-12=20 位,页表项数 2^20 = 1M,每项 4 B,共 4 MB。这就是采用多级页表降低空间的动机。',
 '408真题样式'),
-- 68
((SELECT id FROM knowledge_nodes WHERE title='内存管理-分段' LIMIT 1),
 'CHOICE',
 '关于分段存储管理的描述,错误的是:',
 '["A.每段是一个逻辑单位,长度可变", "B.段表项含段号、段基址、段长", "C.段间地址连续,段内地址不连续", "D.分段便于实现共享和保护"]'::jsonb,
 'C',
 '段内地址连续(线性);段间地址在物理内存上不要求连续。分段按程序逻辑划分,便于按段实现共享与保护。',
 '408真题样式'),
-- 69
((SELECT id FROM knowledge_nodes WHERE title='虚拟内存管理' LIMIT 1),
 'CHOICE',
 '在请求分页系统中,某进程访问页面顺序为 1,2,3,4,1,2,5,1,2,3,4,5,采用 LRU 算法,内存 3 个页框,缺页次数为:',
 '["A.7", "B.8", "C.9", "D.10"]'::jsonb,
 'D',
 'LRU 模拟:1(缺)、2(缺)、3(缺)、4(换1,缺)、1(换2,缺)、2(换3,缺)、5(换4,缺)、1(命中)、2(命中)、3(换5,缺)、4(换1,缺)、5(换2,缺),共 10 次缺页。',
 '408真题样式'),
-- 70
((SELECT id FROM knowledge_nodes WHERE title='页面置换-LRU实现' LIMIT 1),
 'CHOICE',
 '关于 OPT(最优)页面置换算法,下列说法正确的是:',
 '["A.可在实际系统中实现", "B.缺页率最低,但不可实现,常用作性能基准", "C.置换最近最久未使用的页", "D.置换最先调入的页"]'::jsonb,
 'B',
 'OPT 选择"未来最长时间不会被访问"的页置换,需先知未来访问串,实际不可实现,但被作为最优基准用以评价 LRU、FIFO 等。',
 '408真题样式'),
-- 71
((SELECT id FROM knowledge_nodes WHERE title='工作集与抖动' LIMIT 1),
 'CHOICE',
 '系统抖动(thrashing)的主要原因是:',
 '["A.CPU 速度太慢", "B.分配给进程的页框过少,导致频繁缺页", "C.磁盘容量不足", "D.使用了 LRU 算法"]'::jsonb,
 'B',
 '抖动的本质是进程的工作集大于分得页框,频繁缺页置换,CPU 大部分时间用于 I/O 调页而非有效计算。',
 '408真题样式'),
-- 72
((SELECT id FROM knowledge_nodes WHERE title='快表TLB' LIMIT 1),
 'CHOICE',
 'TLB 的主要作用是:',
 '["A.缓存最近使用的页表项,加速地址变换", "B.缓存最近访问的数据", "C.存放主存数据的副本", "D.存放磁盘数据"]'::jsonb,
 'A',
 'TLB(快表)是 MMU 内的小型相联存储器,缓存常用页表项。命中时无需访问主存中的页表,大幅减少地址变换时间。',
 '408真题样式'),
-- 73
((SELECT id FROM knowledge_nodes WHERE title='文件系统' LIMIT 1),
 'CHOICE',
 '在 UNIX 文件系统中,用于保存文件元数据(权限、大小、数据块指针等)的结构称为:',
 '["A.目录项", "B.索引节点(inode)", "C.超级块", "D.主引导记录"]'::jsonb,
 'B',
 'inode 存放文件除文件名外的所有元数据,目录项只保存文件名到 inode 号的映射。同一文件可被多个目录项硬链接到同一 inode。',
 '408真题样式'),
-- 74
((SELECT id FROM knowledge_nodes WHERE title='文件系统' LIMIT 1),
 'CHOICE',
 '关于文件物理结构,下列描述正确的是:',
 '["A.连续分配支持随机访问且无外部碎片", "B.链接分配支持随机访问效率高", "C.索引分配支持随机访问且不需要连续空间", "D.索引分配相比链接分配空间利用率更低"]'::jsonb,
 'C',
 '索引分配建立索引表存所有数据块号,O(1) 随机访问且文件可分散存储。连续分配会有外部碎片;链接分配只能顺序访问。',
 '408真题样式'),
-- 75
((SELECT id FROM knowledge_nodes WHERE title='磁盘调度算法' LIMIT 1),
 'CHOICE',
 '磁盘当前磁头在 100 号磁道,请求队列依次为 55,58,39,18,90,160,150,38,184。采用 SCAN 算法(磁头当前向磁道号增大方向移动),则磁头移动总磁道数为:',
 '["A.398", "B.331", "C.280", "D.450"]'::jsonb,
 'B',
 'SCAN 向外扫:100->150->160->184(到端 199),折返->90->58->55->39->38->18。距离 84+(184-18) = 84+247 = 331。注:不到边界 199 而是到最大请求 184 折返时为 84+(184-18)=331,与精确公式一致。',
 '408真题样式'),
-- 76
((SELECT id FROM knowledge_nodes WHERE title='磁盘调度算法' LIMIT 1),
 'CHOICE',
 '下列磁盘调度算法中,可能产生饥饿的是:',
 '["A.FCFS", "B.SSTF", "C.SCAN", "D.C-SCAN"]'::jsonb,
 'B',
 'SSTF 总选离当前磁头最近的请求,远磁道请求可能长期得不到服务而饥饿。FCFS 公平,SCAN/C-SCAN 由于固定扫描方向也不会饥饿。',
 '408真题样式'),
-- 77
((SELECT id FROM knowledge_nodes WHERE title='系统调用' LIMIT 1),
 'CHOICE',
 '下列操作中,属于必须通过系统调用才能完成的是:',
 '["A.整数加法运算", "B.读取文件内容", "C.局部变量赋值", "D.条件分支"]'::jsonb,
 'B',
 '读文件涉及内核 I/O 服务,需通过系统调用陷入内核态完成。其他三项是用户态指令直接执行。',
 '408真题样式'),
-- 78
((SELECT id FROM knowledge_nodes WHERE title='进程通信IPC' LIMIT 1),
 'CHOICE',
 '下列进程通信方式中,数据交换效率最高的通常是:',
 '["A.管道", "B.消息队列", "C.共享内存", "D.套接字"]'::jsonb,
 'C',
 '共享内存让多进程映射同一物理页,直接读写无需内核拷贝,效率最高。其他方式都需经内核中转。',
 '408真题样式'),
-- 79
((SELECT id FROM knowledge_nodes WHERE title='管程' LIMIT 1),
 'CHOICE',
 '关于管程,下列说法正确的是:',
 '["A.管程是一种硬件机制", "B.管程内的过程任意时刻最多只允许一个进程执行", "C.管程不需要条件变量", "D.管程不能解决生产者—消费者问题"]'::jsonb,
 'B',
 '管程将共享变量与对其的操作封装,通过编译器保证互斥(同一时刻只 1 进程进入管程),并使用条件变量(wait/signal)实现同步。',
 '408真题样式'),
-- 80
((SELECT id FROM knowledge_nodes WHERE title='用户态与内核态' LIMIT 1),
 'CHOICE',
 '下列指令中,属于特权指令(只能在内核态执行)的是:',
 '["A.算术加法指令", "B.读取通用寄存器指令", "C.设置时钟中断指令", "D.条件跳转指令"]'::jsonb,
 'C',
 '设置时钟、关中断、修改 PSW 等会影响系统全局,必须在内核态执行,称为特权指令。普通运算/访存指令在用户态即可。',
 '408真题样式');

-- ========================================================================
-- 408 计算机网络 (topic_id=17) — 20 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 81
((SELECT id FROM knowledge_nodes WHERE title='计算机网络体系结构' LIMIT 1),
 'CHOICE',
 'OSI 参考模型自底向上的第 4 层是:',
 '["A.网络层", "B.传输层", "C.会话层", "D.数据链路层"]'::jsonb,
 'B',
 'OSI 七层:1物理 2数据链路 3网络 4传输 5会话 6表示 7应用。第 4 层即传输层,负责端到端通信。',
 '408真题样式'),
-- 82
((SELECT id FROM knowledge_nodes WHERE title='物理层基础' LIMIT 1),
 'CHOICE',
 '某信道带宽 4 kHz,信噪比 30 dB,根据香农公式,信道极限速率约为:',
 '["A.4 kbps", "B.12 kbps", "C.40 kbps", "D.4 Mbps"]'::jsonb,
 'C',
 'C = W*log2(1+S/N),30 dB 即 S/N=1000,log2(1001)≈10,C≈4*10=40 kbps。',
 '408真题样式'),
-- 83
((SELECT id FROM knowledge_nodes WHERE title='数据链路层-差错控制' LIMIT 1),
 'CHOICE',
 '采用 CRC 校验,生成多项式 G(x)=x^3+x+1 (即 1011),数据为 1101,则校验码为:',
 '["A.001", "B.010", "C.011", "D.110"]'::jsonb,
 'B',
 '数据 1101 后补 3 个 0 得 1101000,除 1011 模 2 除法,商 1110 余 010,故校验码 010,实际发送 1101010。',
 '408真题样式'),
-- 84
((SELECT id FROM knowledge_nodes WHERE title='数据链路层-流量控制' LIMIT 1),
 'CHOICE',
 '在 GBN 协议中,若发送窗口大小为 W,序号采用 n 位编号,则 W 必须满足:',
 '["A.W <= 2^n", "B.W <= 2^n - 1", "C.W <= 2^(n-1)", "D.W <= 2^(n-1) - 1"]'::jsonb,
 'B',
 'GBN 接收窗口=1,发送窗口最大 2^n - 1。否则可能出现新旧序号混淆。SR 协议则要求发+收<=2^n,各 2^(n-1)。',
 '408真题样式'),
-- 85
((SELECT id FROM knowledge_nodes WHERE title='以太网(IEEE 802.3)' LIMIT 1),
 'CHOICE',
 '以太网 CSMA/CD 协议中,最小帧长 64 字节的设定与下列哪个量直接相关?',
 '["A.带宽", "B.链路传播时延的 2 倍(争用期)", "C.介质长度上限", "D.MAC 地址长度"]'::jsonb,
 'B',
 '最小帧长保证发送方在传完帧前能检测到冲突,即 帧长/带宽 >= 2*单程传播时延。10Mbps 以太网取 51.2 us 争用期对应 512 bit=64 B。',
 '408真题样式'),
-- 86
((SELECT id FROM knowledge_nodes WHERE title='以太网(IEEE 802.3)' LIMIT 1),
 'CHOICE',
 'MAC 地址的长度是:',
 '["A.4 字节", "B.6 字节", "C.8 字节", "D.16 字节"]'::jsonb,
 'B',
 'MAC 地址 48 位 = 6 字节,通常用 12 个十六进制数表示,如 00-1A-2B-3C-4D-5E,前 24 位为厂商 OUI。',
 '408真题样式'),
-- 87
((SELECT id FROM knowledge_nodes WHERE title='IP协议' LIMIT 1),
 'CHOICE',
 'IP 地址 192.168.1.130/26 所在子网的网络地址是:',
 '["A.192.168.1.0", "B.192.168.1.64", "C.192.168.1.128", "D.192.168.1.192"]'::jsonb,
 'C',
 '/26 子网掩码 255.255.255.192,主机位 6 位,块大小 64。130 落在 [128,191] 区间,网络地址 192.168.1.128。',
 '408真题样式'),
-- 88
((SELECT id FROM knowledge_nodes WHERE title='IP协议' LIMIT 1),
 'CHOICE',
 '一个 C 类网络借 3 位作子网号,每个子网最多可容纳的主机数为:',
 '["A.30", "B.32", "C.62", "D.64"]'::jsonb,
 'A',
 'C 类主机位原 8 位,借 3 位剩 5 位,主机数 = 2^5 - 2 = 30(去掉全 0 网络地址和全 1 广播地址)。',
 '408真题样式'),
-- 89
((SELECT id FROM knowledge_nodes WHERE title='ARP协议' LIMIT 1),
 'CHOICE',
 '主机 A 要向同一以太网中的主机 B 发送数据,A 已知 B 的 IP 地址但不知 MAC 地址,A 首先要做:',
 '["A.广播 ARP 请求获取 B 的 MAC", "B.单播 ARP 请求", "C.直接发送数据帧", "D.通过 DNS 查询"]'::jsonb,
 'A',
 'ARP 请求以广播方式发送,询问"谁的 IP 是 X.X.X.X",对应主机以单播 ARP 应答返回其 MAC 地址,A 缓存后再封装数据帧发出。',
 '408真题样式'),
-- 90
((SELECT id FROM knowledge_nodes WHERE title='路由算法' LIMIT 1),
 'CHOICE',
 '关于 RIP 与 OSPF 协议,下列说法正确的是:',
 '["A.RIP 用链路状态算法,OSPF 用距离向量", "B.RIP 用距离向量,OSPF 用链路状态", "C.两者都用最短路径算法 Dijkstra", "D.RIP 收敛速度比 OSPF 快"]'::jsonb,
 'B',
 'RIP 基于距离向量,周期性向邻居广播路由表,跳数限 15,收敛慢易振荡;OSPF 基于链路状态泛洪、各路由器跑 Dijkstra,收敛快、规模大。',
 '408真题样式'),
-- 91
((SELECT id FROM knowledge_nodes WHERE title='ICMP协议' LIMIT 1),
 'CHOICE',
 '下列哪个工具利用 ICMP 协议工作?',
 '["A.Telnet", "B.FTP", "C.Ping", "D.SSH"]'::jsonb,
 'C',
 'Ping 通过发送 ICMP Echo Request 并接收 Echo Reply 测试网络连通性。Traceroute 也利用 ICMP 超时报文。Telnet/FTP/SSH 在 TCP 之上。',
 '408真题样式'),
-- 92
((SELECT id FROM knowledge_nodes WHERE title='TCP协议' LIMIT 1),
 'CHOICE',
 '关于 TCP 协议,下列描述错误的是:',
 '["A.面向连接", "B.可靠传输,提供按序递交", "C.面向报文,保留报文边界", "D.支持全双工通信"]'::jsonb,
 'C',
 'TCP 面向字节流,不保留消息边界,接收端可能一次读到多个发送报文的内容,需自行分包。"面向报文"是 UDP 的特征。',
 '408真题样式'),
-- 93
((SELECT id FROM knowledge_nodes WHERE title='TCP三次握手与四次挥手' LIMIT 1),
 'CHOICE',
 'TCP 连接建立时为什么需要三次握手而不是两次?',
 '["A.两次握手会浪费带宽", "B.两次握手无法防止已失效的连接请求突然到达造成错误连接", "C.三次握手能加密通信", "D.两次握手不支持双向数据"]'::jsonb,
 'B',
 '若仅两次,旧 SYN 滞留再到达会让服务器误以为新连接,占用资源。三次握手让客户端最后再确认一次,可丢弃过期请求。',
 '408真题样式'),
-- 94
((SELECT id FROM knowledge_nodes WHERE title='TCP三次握手与四次挥手' LIMIT 1),
 'CHOICE',
 'TCP 主动关闭方进入 TIME_WAIT 状态后,需等待:',
 '["A.MSL", "B.2*MSL", "C.RTT", "D.立即关闭"]'::jsonb,
 'B',
 'TIME_WAIT 等 2*MSL 是为了:1) 让对方未收到 ACK 时能重传 FIN,本端能再回 ACK;2) 让本连接报文在网络中消失,避免与新连接混淆。',
 '408真题样式'),
-- 95
((SELECT id FROM knowledge_nodes WHERE title='TCP流量控制' LIMIT 1),
 'CHOICE',
 'TCP 通过哪种机制实现流量控制?',
 '["A.滑动窗口(由接收方通告)", "B.令牌环", "C.CSMA/CD", "D.漏桶算法"]'::jsonb,
 'A',
 '接收方在 ACK 中通过 Window 字段告知当前可接收字节数,发送方据此调整发送窗口,匹配接收能力,这就是基于滑动窗口的流量控制。',
 '408真题样式'),
-- 96
((SELECT id FROM knowledge_nodes WHERE title='TCP拥塞控制' LIMIT 1),
 'CHOICE',
 'TCP 拥塞控制中,慢开始阶段拥塞窗口 cwnd 的增长方式是:',
 '["A.线性增长(每 RTT +1)", "B.指数增长(每 RTT 翻倍)", "C.保持不变", "D.乘性减小"]'::jsonb,
 'B',
 '慢开始时每收到一个 ACK 就 cwnd+=1,一个 RTT 后 cwnd 大约翻倍,呈指数增长,直到达到 ssthresh 进入拥塞避免阶段(线性增)。',
 '408真题样式'),
-- 97
((SELECT id FROM knowledge_nodes WHERE title='UDP协议' LIMIT 1),
 'CHOICE',
 'UDP 首部包含的字段不包括:',
 '["A.源端口", "B.目的端口", "C.长度", "D.序列号"]'::jsonb,
 'D',
 'UDP 头 8 字节:源端口、目的端口、长度、校验和,各 2 字节。无序号、无确认号,因为 UDP 不提供可靠传输。',
 '408真题样式'),
-- 98
((SELECT id FROM knowledge_nodes WHERE title='DNS域名系统' LIMIT 1),
 'CHOICE',
 '下列关于 DNS 解析的说法,错误的是:',
 '["A.DNS 默认使用 UDP 53 端口", "B.递归查询要求被询问的服务器要么给出答案,要么代为查询", "C.迭代查询每一步都返回下一步要询问的服务器", "D.根域名服务器只有 13 个 IP 地址,因此全球只有 13 台物理服务器"]'::jsonb,
 'D',
 '根域名"逻辑上"13 个 IP,实际全球通过 anycast 部署了数百台镜像服务器响应同一 IP,以提高可用性和就近服务。',
 '408真题样式'),
-- 99
((SELECT id FROM knowledge_nodes WHERE title='HTTP协议' LIMIT 1),
 'CHOICE',
 'HTTP/1.1 默认采用持久连接(Keep-Alive),其主要好处是:',
 '["A.支持加密通信", "B.同一 TCP 连接上可发送多个请求/响应,减少握手开销", "C.允许并行多请求", "D.改善缓存机制"]'::jsonb,
 'B',
 '持久连接复用 TCP 连接,避免每次请求重新三次握手,降低延时和开销。HTTP/1.1 还支持流水线但浏览器实际较少使用。',
 '408真题样式'),
-- 100
((SELECT id FROM knowledge_nodes WHERE title='HTTPS与网络安全' LIMIT 1),
 'CHOICE',
 'HTTPS 在 HTTP 之下、TCP 之上引入的协议是:',
 '["A.IPsec", "B.SSH", "C.TLS/SSL", "D.PGP"]'::jsonb,
 'C',
 'HTTPS = HTTP over TLS/SSL,在传输层之上、应用层之下加密整个 HTTP 报文,使用对称加密+非对称握手+证书验证服务端身份。',
 '408真题样式');

-- ========================================================================
-- 数学一 高等数学 (topic_id=11) — 20 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 101
((SELECT id FROM knowledge_nodes WHERE title='函数与极限' LIMIT 1),
 'CHOICE',
 '极限 lim[x→0] (sin x)/x 的值为:',
 '["A.0", "B.1", "C.无穷大", "D.不存在"]'::jsonb,
 'B',
 '这是第一个重要极限 lim[x→0] sin(x)/x = 1,可由几何夹逼或 Taylor 展开 sin(x)=x-x^3/6+... 得到。',
 '数学一真题样式'),
-- 102
((SELECT id FROM knowledge_nodes WHERE title='函数与极限' LIMIT 1),
 'CHOICE',
 '极限 lim[x→∞] (1+1/x)^x 的值为:',
 '["A.0", "B.1", "C.e", "D.不存在"]'::jsonb,
 'C',
 '第二个重要极限 lim[x→∞] (1+1/x)^x = e,这是自然对数底 e 的定义之一。',
 '数学一真题样式'),
-- 103
((SELECT id FROM knowledge_nodes WHERE title='无穷小与无穷大' LIMIT 1),
 'CHOICE',
 '当 x→0 时,下列哪个函数与 x 是同阶但非等价的无穷小?',
 '["A.sin x", "B.tan x", "C.1-cos x", "D.2x"]'::jsonb,
 'D',
 '同阶无穷小要求 lim 比值为非零常数,等价要求该常数为 1。lim 2x/x = 2,同阶非等价。A、B 等价于 x;C 是 x 的二阶无穷小,与 x 不同阶。',
 '数学一真题样式'),
-- 104
((SELECT id FROM knowledge_nodes WHERE title='函数连续性' LIMIT 1),
 'CHOICE',
 '函数 f(x) = (x^2-1)/(x-1) 在 x=1 处的间断点类型是:',
 '["A.第一类可去间断点", "B.第一类跳跃间断点", "C.第二类无穷间断点", "D.第二类振荡间断点"]'::jsonb,
 'A',
 'x 不等于 1 时 f(x)=x+1,lim[x→1]=2 存在但 f(1) 未定义,属第一类可去间断点。补充定义 f(1)=2 即可连续。',
 '数学一真题样式'),
-- 105
((SELECT id FROM knowledge_nodes WHERE title='导数定义' LIMIT 1),
 'CHOICE',
 '设 f 在 x=a 处可导,则 lim[h→0] [f(a+2h) - f(a-h)] / h 等于:',
 '["A.f^(1)(a)", "B.2*f^(1)(a)", "C.3*f^(1)(a)", "D.0"]'::jsonb,
 'C',
 '原式 = lim [f(a+2h)-f(a)]/h + lim [f(a)-f(a-h)]/h = 2*f^(1)(a) + 1*f^(1)(a) = 3*f^(1)(a)。',
 '数学一真题样式'),
-- 106
((SELECT id FROM knowledge_nodes WHERE title='求导法则' LIMIT 1),
 'CHOICE',
 '设 y = ln(sin x),则其一阶导数为:',
 '["A.cot x", "B.tan x", "C.-cot x", "D.-tan x"]'::jsonb,
 'A',
 '由复合求导:dy/dx = (1/sin x)*cos x = cos x/sin x = cot x。',
 '数学一真题样式'),
-- 107
((SELECT id FROM knowledge_nodes WHERE title='高阶导数' LIMIT 1),
 'CHOICE',
 '函数 f(x) = e^x * sin x 的二阶导 f^(2)(x) 等于:',
 '["A.2*e^x * cos x", "B.2*e^x * sin x", "C.e^x * sin x", "D.0"]'::jsonb,
 'A',
 '一阶 f^(1) = e^x*(sin x + cos x);二阶 f^(2) = e^x*(sin x+cos x) + e^x*(cos x-sin x) = 2*e^x*cos x。',
 '数学一真题样式'),
-- 108
((SELECT id FROM knowledge_nodes WHERE title='微分中值定理' LIMIT 1),
 'CHOICE',
 '关于拉格朗日中值定理,下列说法正确的是:',
 '["A.要求 f 在闭区间上连续,在开区间上可导", "B.结论是 f(b)=f(a)", "C.要求 f 在区间端点取相同值", "D.结论是存在导数的零点"]'::jsonb,
 'A',
 '拉格朗日条件:闭区间连续+开区间可导,结论:存在 ξ 使 f(b)-f(a)=f^(1)(ξ)*(b-a)。要求端点相同的是罗尔定理。',
 '数学一真题样式'),
-- 109
((SELECT id FROM knowledge_nodes WHERE title='洛必达法则' LIMIT 1),
 'CHOICE',
 '极限 lim[x→0] (e^x - 1 - x)/x^2 等于:',
 '["A.0", "B.1/2", "C.1", "D.2"]'::jsonb,
 'B',
 '0/0 型,洛必达两次:lim (e^x-1)/(2x) = lim e^x / 2 = 1/2。或用 Taylor: e^x=1+x+x^2/2+...,分子 ~ x^2/2,极限 1/2。',
 '数学一真题样式'),
-- 110
((SELECT id FROM knowledge_nodes WHERE title='泰勒公式' LIMIT 1),
 'CHOICE',
 '函数 f(x)=ln(1+x) 在 x=0 的 Taylor 展开,前三项是:',
 '["A.x - x^2/2 + x^3/3", "B.x + x^2/2 + x^3/3", "C.1 + x - x^2/2", "D.x - x^2 + x^3"]'::jsonb,
 'A',
 'ln(1+x) = sum_{n>=1} (-1)^(n-1) x^n /n = x - x^2/2 + x^3/3 - ... 收敛半径 R=1。',
 '数学一真题样式'),
-- 111
((SELECT id FROM knowledge_nodes WHERE title='单调性与极值' LIMIT 1),
 'CHOICE',
 '函数 f(x) = x^3 - 3x 的极小值为:',
 '["A.-2", "B.0", "C.2", "D.-4"]'::jsonb,
 'A',
 'f^(1)(x)=3x^2-3=0 得 x=±1,f^(2)(x)=6x。x=1 处 f^(2)>0 取极小,f(1)=1-3=-2。',
 '数学一真题样式'),
-- 112
((SELECT id FROM knowledge_nodes WHERE title='凹凸性与拐点' LIMIT 1),
 'CHOICE',
 '函数 f(x) = x^3 - 3x^2 的拐点是:',
 '["A.(0, 0)", "B.(1, -2)", "C.(2, -4)", "D.(-1, -4)"]'::jsonb,
 'B',
 'f^(2)(x)=6x-6=0 得 x=1,且 x<1 时 f^(2)<0 凹,x>1 时 f^(2)>0 凸,凹凸性改变,拐点为 (1, 1-3)=(1,-2)。',
 '数学一真题样式'),
-- 113
((SELECT id FROM knowledge_nodes WHERE title='不定积分' LIMIT 1),
 'CHOICE',
 '∫ x*e^x dx 等于:',
 '["A.x*e^x + C", "B.(x-1)*e^x + C", "C.(x+1)*e^x + C", "D.x^2/2 * e^x + C"]'::jsonb,
 'B',
 '分部积分 u=x, dv=e^x dx,得 x*e^x - ∫ e^x dx = x*e^x - e^x + C = (x-1)*e^x + C。',
 '数学一真题样式'),
-- 114
((SELECT id FROM knowledge_nodes WHERE title='定积分' LIMIT 1),
 'CHOICE',
 '∫[0,π/2] sin^2 x dx 等于:',
 '["A.π/4", "B.π/2", "C.1/2", "D.1"]'::jsonb,
 'A',
 '用半角公式 sin^2 x = (1-cos 2x)/2,积分 = x/2 - sin(2x)/4 |[0,π/2] = π/4 - 0 = π/4。',
 '数学一真题样式'),
-- 115
((SELECT id FROM knowledge_nodes WHERE title='反常积分' LIMIT 1),
 'CHOICE',
 '反常积分 ∫[1,∞) 1/x^p dx 收敛的充要条件是:',
 '["A.p > 0", "B.p > 1", "C.p < 1", "D.p >= 1"]'::jsonb,
 'B',
 'p>1 时积分=1/(p-1) 收敛;p=1 时为 ln x 发散;p<1 时也发散。这是 p 级数判别中的重要结论。',
 '数学一真题样式'),
-- 116
((SELECT id FROM knowledge_nodes WHERE title='数项级数收敛性' LIMIT 1),
 'CHOICE',
 '级数 sum (n>=1) 1/n^p 收敛的充要条件是:',
 '["A.p > 0", "B.p > 1", "C.p >= 1", "D.p < 1"]'::jsonb,
 'B',
 '这是 p 级数:p>1 收敛(用积分判别法对照 ∫ 1/x^p),p<=1 发散。p=1 即调和级数发散。',
 '数学一真题样式'),
-- 117
((SELECT id FROM knowledge_nodes WHERE title='幂级数' LIMIT 1),
 'CHOICE',
 '幂级数 sum (n>=0) x^n / n! 的收敛半径为:',
 '["A.1", "B.e", "C.0", "D.+∞"]'::jsonb,
 'D',
 '比值法:lim |a_(n+1)/a_n| = lim 1/(n+1) = 0,故 R = 1/0 = +∞,即对所有实数收敛,该级数和为 e^x。',
 '数学一真题样式'),
-- 118
((SELECT id FROM knowledge_nodes WHERE title='二阶常系数齐次线性微分方程' LIMIT 1),
 'CHOICE',
 '微分方程 y^(2) - 5*y^(1) + 6y = 0 的通解是:',
 '["A.y = C1*e^(2x) + C2*e^(3x)", "B.y = C1*e^(-2x) + C2*e^(-3x)", "C.y = (C1+C2*x)*e^(2x)", "D.y = e^x(C1*cos x + C2*sin x)"]'::jsonb,
 'A',
 '特征方程 r^2-5r+6=0,根 r1=2,r2=3 实不等,通解 y=C1*e^(2x)+C2*e^(3x)。',
 '数学一真题样式'),
-- 119
((SELECT id FROM knowledge_nodes WHERE title='一阶可分离微分方程' LIMIT 1),
 'CHOICE',
 '微分方程 dy/dx = y/x 的通解是:',
 '["A.y = Cx", "B.y = C/x", "C.y = x + C", "D.y = C*e^x"]'::jsonb,
 'A',
 '分离变量 dy/y = dx/x,积分得 ln|y| = ln|x| + C1,即 y = Cx。',
 '数学一真题样式'),
-- 120
((SELECT id FROM knowledge_nodes WHERE title='偏导数' LIMIT 1),
 'CHOICE',
 '设 z = x^2 + 3xy + y^2,则 ∂z/∂x 在点 (1,2) 处的值为:',
 '["A.5", "B.7", "C.8", "D.10"]'::jsonb,
 'C',
 '∂z/∂x = 2x + 3y,代入 (1,2) 得 2+6 = 8。',
 '数学一真题样式');

-- ========================================================================
-- 数学一 线性代数 (topic_id=12) — 15 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 121
((SELECT id FROM knowledge_nodes WHERE title='行列式定义' LIMIT 1),
 'CHOICE',
 '关于 n 阶行列式,下列性质错误的是:',
 '["A.行列式与其转置相等", "B.交换两行,行列式变号", "C.两行成比例,行列式为零", "D.某行乘 k 倍,行列式乘 k^n"]'::jsonb,
 'D',
 '只有"某一行乘 k"时行列式乘 k(线性性);而"整个矩阵乘 k"才是 k^n 倍。这是常见易错点。',
 '数学一真题样式'),
-- 122
((SELECT id FROM knowledge_nodes WHERE title='行列式计算' LIMIT 1),
 'CHOICE',
 '行列式 |1 2; 3 4| (二阶) 的值为:',
 '["A.-2", "B.2", "C.10", "D.-10"]'::jsonb,
 'A',
 '二阶行列式 = ad - bc = 1*4 - 2*3 = 4 - 6 = -2。',
 '数学一真题样式'),
-- 123
((SELECT id FROM knowledge_nodes WHERE title='矩阵运算' LIMIT 1),
 'CHOICE',
 '设 A、B 都是 n 阶矩阵,下列等式恒成立的是:',
 '["A.AB = BA", "B.(A+B)^2 = A^2 + 2AB + B^2", "C.(AB)^T = B^T * A^T", "D.det(A+B) = det(A) + det(B)"]'::jsonb,
 'C',
 '矩阵转置满足 (AB)^T = B^T * A^T。乘法不交换;平方公式不展开;行列式不可加。',
 '数学一真题样式'),
-- 124
((SELECT id FROM knowledge_nodes WHERE title='逆矩阵' LIMIT 1),
 'CHOICE',
 'n 阶矩阵 A 可逆的充要条件是:',
 '["A.A 是方阵", "B.det(A) ≠ 0", "C.A 的元素全部非零", "D.A 是上三角矩阵"]'::jsonb,
 'B',
 '矩阵可逆 ⇔ |A|≠0 ⇔ A 满秩 ⇔ A 的列(行)向量线性无关 ⇔ Ax=0 只有零解。',
 '数学一真题样式'),
-- 125
((SELECT id FROM knowledge_nodes WHERE title='伴随矩阵' LIMIT 1),
 'CHOICE',
 '设 A 为 n 阶矩阵,A^* 为伴随矩阵,则 A * A^* 等于:',
 '["A.0", "B.E (单位阵)", "C.|A| * E", "D.|A|^n * E"]'::jsonb,
 'C',
 '伴随矩阵的基本关系式 A*A^* = A^**A = |A|*E。当 |A|≠0 时,A^(-1) = A^*/|A|。',
 '数学一真题样式'),
-- 126
((SELECT id FROM knowledge_nodes WHERE title='矩阵的秩' LIMIT 1),
 'CHOICE',
 '设 A 为 m*n 矩阵,则 r(A) 满足:',
 '["A.r(A) <= min(m, n)", "B.r(A) = m", "C.r(A) = n", "D.r(A) = m + n"]'::jsonb,
 'A',
 '矩阵的秩既不超过行数也不超过列数,故 r(A) <= min(m,n)。当 r(A) = min(m,n) 时称行/列满秩。',
 '数学一真题样式'),
-- 127
((SELECT id FROM knowledge_nodes WHERE title='向量组的线性相关性' LIMIT 1),
 'CHOICE',
 '设 α1, α2, α3 是三维向量,若 r(α1, α2, α3) = 2,则:',
 '["A.三向量线性无关", "B.三向量线性相关", "C.其中任两个线性相关", "D.三向量都为零向量"]'::jsonb,
 'B',
 '秩=2<3 表明向量组线性相关;但其中存在 2 个线性无关的(极大无关组),其余为它们的线性组合。',
 '数学一真题样式'),
-- 128
((SELECT id FROM knowledge_nodes WHERE title='齐次线性方程组' LIMIT 1),
 'CHOICE',
 '设 A 为 m*n 矩阵,齐次方程组 Ax=0 有非零解的充要条件是:',
 '["A.r(A) = n", "B.r(A) < n", "C.r(A) = m", "D.m = n"]'::jsonb,
 'B',
 '齐次方程组解空间维数 = n - r(A)。要有非零解必须 r(A) < n。当 m<n 时必有 r(A)<=m<n,自然成立。',
 '数学一真题样式'),
-- 129
((SELECT id FROM knowledge_nodes WHERE title='非齐次线性方程组' LIMIT 1),
 'CHOICE',
 '非齐次线性方程组 Ax=b 有解的充要条件是:',
 '["A.r(A) = n", "B.r(A,b) = m", "C.r(A) = r(A,b)", "D.|A| ≠ 0"]'::jsonb,
 'C',
 '系数矩阵秩 = 增广矩阵秩,即 b 落在 A 的列空间中。若 r(A)=r(A,b)=n 解唯一,r(A)=r(A,b)<n 有无穷多解。',
 '数学一真题样式'),
-- 130
((SELECT id FROM knowledge_nodes WHERE title='特征值与特征向量' LIMIT 1),
 'CHOICE',
 '矩阵 A = |2 1; 0 3| 的特征值为:',
 '["A.1 和 2", "B.2 和 3", "C.0 和 5", "D.-1 和 6"]'::jsonb,
 'B',
 '上三角矩阵的特征值 = 主对角线元素,即 2 和 3。也可由 |λE-A|=(λ-2)(λ-3)=0 验证。',
 '数学一真题样式'),
-- 131
((SELECT id FROM knowledge_nodes WHERE title='相似矩阵' LIMIT 1),
 'CHOICE',
 '关于相似矩阵 A 与 B (A ~ B),下列性质错误的是:',
 '["A.|A| = |B|", "B.r(A) = r(B)", "C.特征多项式相同", "D.A 与 B 的元素对应相等"]'::jsonb,
 'D',
 '相似矩阵保持迹、行列式、秩、特征值、特征多项式等不变,但元素值并不相等。这是相似的定义本质。',
 '数学一真题样式'),
-- 132
((SELECT id FROM knowledge_nodes WHERE title='矩阵对角化' LIMIT 1),
 'CHOICE',
 'n 阶矩阵 A 可对角化的充要条件是:',
 '["A.A 有 n 个不同的特征值", "B.A 是对称矩阵", "C.A 有 n 个线性无关的特征向量", "D.|A| ≠ 0"]'::jsonb,
 'C',
 'A 可对角化 ⇔ 存在 n 个线性无关的特征向量构成可逆矩阵 P,使 P^(-1)*A*P = 对角阵。A 项是充分而非必要条件。',
 '数学一真题样式'),
-- 133
((SELECT id FROM knowledge_nodes WHERE title='实对称矩阵对角化' LIMIT 1),
 'CHOICE',
 '关于实对称矩阵 A,下列说法错误的是:',
 '["A.A 必定可对角化", "B.A 的特征值都是实数", "C.A 不同特征值对应的特征向量正交", "D.A 的特征值都为正"]'::jsonb,
 'D',
 '实对称矩阵的特征值不必为正(那是正定矩阵的额外条件)。A、B、C 都是实对称矩阵的核心性质。',
 '数学一真题样式'),
-- 134
((SELECT id FROM knowledge_nodes WHERE title='二次型' LIMIT 1),
 'CHOICE',
 '二次型 f(x1, x2) = x1^2 - 2*x1*x2 + 3*x2^2 对应的实对称矩阵是:',
 '["A.|1 -2; 0 3|", "B.|1 -1; -1 3|", "C.|1 -2; -2 3|", "D.|1 1; 1 3|"]'::jsonb,
 'B',
 '二次型对称矩阵 a_{ii} 取 x_i^2 系数,a_{ij}=a_{ji} 取交叉项 x_i*x_j 系数的一半。-2*x1*x2 给 a_{12}=a_{21}=-1。',
 '数学一真题样式'),
-- 135
((SELECT id FROM knowledge_nodes WHERE title='正定二次型' LIMIT 1),
 'CHOICE',
 'n 元二次型 f = x^T A x 正定的充要条件是:',
 '["A.A 的所有元素为正", "B.A 的所有特征值为正", "C.|A| > 0", "D.A 是上三角"]'::jsonb,
 'B',
 '实对称矩阵 A 正定 ⇔ 全部特征值>0 ⇔ 全部顺序主子式>0 ⇔ 合同于单位阵。仅 |A|>0 不足(可能负负相乘)。',
 '数学一真题样式');

-- ========================================================================
-- 数学一 概率论与数理统计 (topic_id=13) — 15 题
-- ========================================================================

INSERT INTO quiz_questions (node_id, question_type, content, options, answer, explanation, source) VALUES
-- 136
((SELECT id FROM knowledge_nodes WHERE title='古典概型与几何概型' LIMIT 1),
 'CHOICE',
 '一袋中装 5 个白球、3 个黑球,任取 2 个,取到都是白球的概率为:',
 '["A.5/14", "B.10/28", "C.5/8", "D.5/16"]'::jsonb,
 'A',
 'P = C(5,2)/C(8,2) = 10/28 = 5/14。等价于 5/8 * 4/7 = 20/56 = 5/14。',
 '数学一真题样式'),
-- 137
((SELECT id FROM knowledge_nodes WHERE title='条件概率' LIMIT 1),
 'CHOICE',
 '设 P(A)=0.4, P(B)=0.3, P(A∪B)=0.6,则 P(B|A) 为:',
 '["A.0.1", "B.0.25", "C.0.5", "D.0.75"]'::jsonb,
 'B',
 'P(AB) = P(A)+P(B)-P(A∪B) = 0.4+0.3-0.6 = 0.1。P(B|A) = P(AB)/P(A) = 0.1/0.4 = 0.25。',
 '数学一真题样式'),
-- 138
((SELECT id FROM knowledge_nodes WHERE title='全概率与贝叶斯公式' LIMIT 1),
 'CHOICE',
 '某厂三车间生产同一产品,产量比 2:3:5,次品率分别为 5%, 4%, 2%。任取一件为次品的概率是:',
 '["A.0.030", "B.0.032", "C.0.035", "D.0.040"]'::jsonb,
 'B',
 '全概率公式:P = 0.2*0.05 + 0.3*0.04 + 0.5*0.02 = 0.010+0.012+0.010 = 0.032。',
 '数学一真题样式'),
-- 139
((SELECT id FROM knowledge_nodes WHERE title='事件独立性' LIMIT 1),
 'CHOICE',
 '设 P(A)=0.5, P(B)=0.4,A 与 B 相互独立,则 P(A∪B) 等于:',
 '["A.0.7", "B.0.9", "C.0.2", "D.0.6"]'::jsonb,
 'A',
 'A、B 独立 ⇒ P(AB)=0.5*0.4=0.2。P(A∪B)=P(A)+P(B)-P(AB)=0.5+0.4-0.2=0.7。',
 '数学一真题样式'),
-- 140
((SELECT id FROM knowledge_nodes WHERE title='二项分布' LIMIT 1),
 'CHOICE',
 '设 X 服从 B(n=10, p=0.4),则 E(X)、D(X) 分别为:',
 '["A.4 和 4", "B.4 和 2.4", "C.10 和 4", "D.6 和 2.4"]'::jsonb,
 'B',
 '二项分布 X~B(n,p):E(X)=np=10*0.4=4,D(X)=np(1-p)=10*0.4*0.6=2.4。',
 '数学一真题样式'),
-- 141
((SELECT id FROM knowledge_nodes WHERE title='泊松分布' LIMIT 1),
 'CHOICE',
 '设 X ~ P(λ=2),则 P(X=0) 等于:',
 '["A.e^(-2)", "B.2*e^(-2)", "C.0", "D.1/2"]'::jsonb,
 'A',
 '泊松分布 P(X=k) = e^(-λ) * λ^k / k!,k=0 时 = e^(-2)。',
 '数学一真题样式'),
-- 142
((SELECT id FROM knowledge_nodes WHERE title='正态分布' LIMIT 1),
 'CHOICE',
 '设 X ~ N(μ, σ^2),则 (X-μ)/σ 服从:',
 '["A.N(μ, σ^2)", "B.N(0, 1)", "C.N(0, σ^2)", "D.N(μ, 1)"]'::jsonb,
 'B',
 '标准化变换 Z=(X-μ)/σ 将一般正态变量化为标准正态 N(0,1),便于查表计算概率。',
 '数学一真题样式'),
-- 143
((SELECT id FROM knowledge_nodes WHERE title='指数分布' LIMIT 1),
 'CHOICE',
 '设 X 服从参数为 λ=1/2 的指数分布,则 E(X)、D(X) 分别为:',
 '["A.1/2 和 1/4", "B.2 和 4", "C.2 和 2", "D.1/2 和 2"]'::jsonb,
 'B',
 '指数分布 E(X)=1/λ=2,D(X)=1/λ^2=4。注意λ是率参数,1/λ才是均值。',
 '数学一真题样式'),
-- 144
((SELECT id FROM knowledge_nodes WHERE title='数学期望' LIMIT 1),
 'CHOICE',
 '设 X、Y 是任意随机变量,a、b 为常数,则下列等式恒成立的是:',
 '["A.E(aX+bY) = aE(X)+bE(Y)", "B.E(XY) = E(X)*E(Y)", "C.D(X+Y) = D(X)+D(Y)", "D.E(X^2) = (E(X))^2"]'::jsonb,
 'A',
 '数学期望具有线性性,无需独立。E(XY)=E(X)E(Y) 与 D(X+Y)=D(X)+D(Y) 都需要 X、Y 独立(或不相关)才成立。',
 '数学一真题样式'),
-- 145
((SELECT id FROM knowledge_nodes WHERE title='方差' LIMIT 1),
 'CHOICE',
 '已知 D(X)=4, D(Y)=9,且 X 与 Y 相互独立,则 D(2X-3Y) 等于:',
 '["A.16+81=97", "B.16+27=43", "C.16-81=-65", "D.97 取负"]'::jsonb,
 'A',
 'D(aX+bY) = a^2*D(X)+b^2*D(Y) (X、Y 独立),= 4*4 + 9*9 = 16+81 = 97。注意系数平方。',
 '数学一真题样式'),
-- 146
((SELECT id FROM knowledge_nodes WHERE title='协方差与相关系数' LIMIT 1),
 'CHOICE',
 '若 X 与 Y 的相关系数 ρ=0,下列说法正确的是:',
 '["A.X 与 Y 一定独立", "B.X 与 Y 不相关", "C.X、Y 必同分布", "D.D(X+Y)=0"]'::jsonb,
 'B',
 'ρ=0 仅说明线性不相关,不一定独立(独立是更强条件)。例外:二维正态分布时,不相关等价于独立。',
 '数学一真题样式'),
-- 147
((SELECT id FROM knowledge_nodes WHERE title='切比雪夫不等式' LIMIT 1),
 'CHOICE',
 '由切比雪夫不等式,P{|X-E(X)| >= ε} 的上界为:',
 '["A.D(X)/ε", "B.D(X)/ε^2", "C.E(X)/ε", "D.1"]'::jsonb,
 'B',
 '切比雪夫不等式:P{|X-EX|>=ε} <= D(X)/ε^2。表明分布越集中(方差越小),偏离均值的概率越小。',
 '数学一真题样式'),
-- 148
((SELECT id FROM knowledge_nodes WHERE title='中心极限定理' LIMIT 1),
 'CHOICE',
 '设 X1, X2, ..., Xn 独立同分布,均值 μ,方差 σ^2,根据中心极限定理,sum X_i 当 n 充分大时近似服从:',
 '["A.N(0,1)", "B.N(nμ, nσ^2)", "C.N(μ, σ^2)", "D.卡方分布"]'::jsonb,
 'B',
 '独立同分布中心极限定理:sum X_i ~近似 N(nμ, nσ^2);标准化后 (sum X_i - nμ)/(σ*√n) ~ N(0,1)。',
 '数学一真题样式'),
-- 149
((SELECT id FROM knowledge_nodes WHERE title='最大似然估计' LIMIT 1),
 'CHOICE',
 '设总体 X ~ N(μ, σ^2),σ^2 已知,样本 X1,...,Xn,μ 的最大似然估计是:',
 '["A.样本中位数", "B.样本均值 X 拔", "C.样本方差", "D.最大值"]'::jsonb,
 'B',
 '正态总体均值的极大似然估计 = 样本均值,这也是矩估计、无偏估计、最小方差无偏估计,具有多种好性质。',
 '数学一真题样式'),
-- 150
((SELECT id FROM knowledge_nodes WHERE title='假设检验' LIMIT 1),
 'CHOICE',
 '在假设检验中,弃真错误(第一类错误)指的是:',
 '["A.原假设 H0 为真却拒绝了 H0", "B.原假设 H0 为假却接受了 H0", "C.原假设 H0 为假且拒绝了 H0", "D.原假设 H0 为真且接受了 H0"]'::jsonb,
 'A',
 '第一类错误(α 错误,弃真):H0 真却被拒绝,概率即显著性水平 α;第二类错误(β 错误,取伪):H0 假却被接受。',
 '数学一真题样式');
